name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.9.2
homepage: https://github.com/fluttercommunity/chewie

publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  video_player:
    url: git@github.com:vanlooverenkoen/flutter-packages.git
    path: packages/video_player/video_player
    ref: 5dd6e139656c778cb32cb65449c45f8f0c2b31e1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
